### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Yerzhaisang** [andredias/perfect_python_project#3]
I see the following error. What can be the reason?

<img width="654" alt="image" src="https://github.com/andredias/perfect_python_project/assets/55043014/cb946ecc-1e6b-4f6d-a0a0-8e5851172370">

**Comment by Yerzhaisang** [comment]
oh, I see
You use /bin/bash, but on the Mac /bin/bash is older than 4th version, so globstar is not supported. Can we fix it so bash is used from $PATH variable?

**Comment by andredias** [comment]
@Yerzhaisang I've made some changes but I can't test on MacOS. Could you please confirm it works now?
