### ISSUE TITLE
programming on windows

### ISSUE THREAD

**Issue by szylmzs** [andredias/perfect_python_project#7]
since uvloop is not supported on windows, so how to program on windows with this template

**Comment by andredias** [comment]
Hi. uvloop is not essential to the template but it is hardcoded there, unfortunately. I'll fix it by detecting the OS during the template instantiation.

**Comment by andredias** [comment]
It is supposed to be solved on 27500c87e4743b0e9cf70d46204eaa11d6ba3ea1. Could you confirm, @szylmzs ?
